import type {
  BlogPost,
  Category,
  CustomerPhoto,
  HeroSlide,
  Product,
  SideBanner,
} from "./types";

// Ảnh khách hàng thực tế tại cửa hàng. Hiện đang là ô placeholder.
// KHI CÓ ẢNH THẬT: upload lên Cloudinary rồi điền URL vào field `image`
// (ví dụ image: "https://res.cloudinary.com/<cloud>/image/upload/w_480,q_auto/khach-1.jpg").
export const CUSTOMER_PHOTOS: CustomerPhoto[] = [
  { id: "kh-1", alt: "Khách hàng nhận laptop tại Chính Nguyễn" },
  { id: "kh-2", alt: "Khách hàng chụp ảnh cùng nhân viên" },
  { id: "kh-3", alt: "Khách hàng nhận MacBook mới" },
  { id: "kh-4", alt: "Khách hàng nhận laptop Dell kèm quà" },
  { id: "kh-5", alt: "Khách hàng hài lòng với sản phẩm" },
  { id: "kh-6", alt: "Khách hàng nhận laptop gaming" },
];

// Banner chính (carousel). Thêm slide = thêm 1 object vào mảng này.
// Khi có ảnh banner thật: bổ sung field ảnh và cho HeroSlideArt render next/image.
export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "uu-dai-thang-7",
    href: "/san-pham",
    badge: "ƯU ĐÃI THÁNG 7",
    title1: "Laptop chính hãng",
    title2: "giá tốt mỗi ngày",
    subtitle: "Trả góp 0% · Bảo hành 24 tháng · Giao nhanh toàn quốc",
    cta: "Mua ngay",
    accent: "green",
  },
  {
    id: "gaming-week",
    href: "/laptop-gaming",
    badge: "GAMING WEEK",
    title1: "Laptop Gaming RTX",
    title2: "giảm đến 20%",
    subtitle: "RTX 4050/4060 · Trả góp 0% · Quà tặng hấp dẫn",
    cta: "Săn deal ngay",
    accent: "blue",
  },
  {
    id: "apple-days",
    href: "/macbook",
    badge: "APPLE DAYS",
    title1: "MacBook chính hãng",
    title2: "trả góp 0%",
    subtitle: "MacBook Air/Pro · Giá tốt nhất Đà Nẵng",
    cta: "Khám phá ngay",
    accent: "purple",
  },
];

// Banner treo 2 bên: phần tử [0] = bên trái, [1] = bên phải.
export const SIDE_BANNERS: SideBanner[] = [
  {
    id: "tra-gop-0",
    href: "/chinh-sach/tra-gop",
    title: "Trả góp 0%",
    subtitle: "Duyệt trong 15 phút",
    accent: "green",
  },
  {
    id: "thu-cu-doi-moi",
    href: "/thu-cu-doi-moi",
    title: "Thu cũ đổi mới",
    subtitle: "Trợ giá đến 3 triệu",
    accent: "blue",
  },
];

// Dữ liệu giả lập cho giai đoạn dựng giao diện. Khi có DB (Prisma),
// thay các hàm getter bên dưới bằng query thật — component không đổi.

export const FLASH_SALE_PRODUCTS: Product[] = [
  {
    id: "p-dell-xps-13-plus-9320",
    slug: "dell-xps-13-plus-9320-i7",
    name: "Dell XPS 13 Plus 9320 i7",
    brand: "Dell",
    price: 28_990_000,
    oldPrice: 34_990_000,
    cpu: "i7-1360P",
    ram: "16GB",
    storage: "512GB",
    rating: 4.8,
    reviewCount: 120,
    installmentPerMonth: 2_416_000,
    gift: "Tặng balo + chuột",
    badge: "-18%",
    accent: "blue",
  },
  {
    id: "p-asus-rog-strix-g16",
    slug: "asus-rog-strix-g16-rtx-4060",
    name: "Asus ROG Strix G16 RTX 4060",
    brand: "Asus",
    price: 32_490_000,
    oldPrice: 41_990_000,
    cpu: "i7-13650HX",
    ram: "16GB",
    storage: "RTX 4060",
    rating: 4.9,
    reviewCount: 86,
    installmentPerMonth: 2_708_000,
    gift: "Tặng balo + tai nghe",
    badge: "-22%",
    accent: "red",
  },
  {
    id: "p-macbook-air-m3-13",
    slug: "macbook-air-m3-13-inch-2024",
    name: "MacBook Air M3 13 inch 2024",
    brand: "MacBook",
    price: 24_990_000,
    oldPrice: 29_490_000,
    cpu: "Apple M3",
    ram: "8GB",
    storage: "256GB",
    rating: 4.9,
    reviewCount: 210,
    installmentPerMonth: 2_082_000,
    gift: "Tặng túi chống sốc",
    badge: "-15%",
    accent: "silver",
  },
  {
    id: "p-lenovo-thinkpad-x1-carbon-g11",
    slug: "lenovo-thinkpad-x1-carbon-g11",
    name: "Lenovo ThinkPad X1 Carbon G11",
    brand: "Lenovo",
    price: 30_490_000,
    oldPrice: 37_990_000,
    cpu: "i7-1355U",
    ram: "16GB",
    storage: "512GB",
    rating: 4.7,
    reviewCount: 54,
    installmentPerMonth: 2_541_000,
    gift: "Tặng balo cao cấp",
    badge: "-20%",
    accent: "crimson",
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "p-dell-inspiron-15-3530",
    slug: "dell-inspiron-15-3530-i5",
    name: "Dell Inspiron 15 3530 i5",
    brand: "Dell",
    price: 15_490_000,
    oldPrice: 17_990_000,
    cpu: "i5-1335U",
    ram: "16GB",
    storage: "512GB",
    rating: 4.6,
    reviewCount: 98,
    installmentPerMonth: 1_291_000,
    gift: "Tặng chuột không dây",
    badge: "-14%",
    accent: "blue",
  },
  {
    id: "p-dell-latitude-5440",
    slug: "dell-latitude-5440-i5",
    name: "Dell Latitude 5440 i5",
    brand: "Dell",
    price: 19_990_000,
    oldPrice: 23_490_000,
    cpu: "i5-1345U",
    ram: "16GB",
    storage: "512GB",
    rating: 4.7,
    reviewCount: 41,
    installmentPerMonth: 1_666_000,
    accent: "dark",
  },
  {
    id: "p-asus-zenbook-14-oled",
    slug: "asus-zenbook-14-oled-ux3405",
    name: "Asus Zenbook 14 OLED UX3405",
    brand: "Asus",
    price: 26_990_000,
    oldPrice: 30_990_000,
    cpu: "Ultra 7 155H",
    ram: "16GB",
    storage: "1TB",
    rating: 4.8,
    reviewCount: 132,
    installmentPerMonth: 2_249_000,
    gift: "Tặng túi chống sốc",
    badge: "-13%",
    isNew: true,
    accent: "silver",
  },
  {
    id: "p-asus-tuf-gaming-f15",
    slug: "asus-tuf-gaming-f15-rtx-3050",
    name: "Asus TUF Gaming F15 RTX 3050",
    brand: "Asus",
    price: 18_990_000,
    oldPrice: 22_490_000,
    cpu: "i5-12500H",
    ram: "16GB",
    storage: "RTX 3050",
    rating: 4.5,
    reviewCount: 76,
    installmentPerMonth: 1_582_000,
    badge: "-15%",
    accent: "red",
  },
  {
    id: "p-acer-aspire-5-a515",
    slug: "acer-aspire-5-a515-i5",
    name: "Acer Aspire 5 A515 i5",
    brand: "Acer",
    price: 13_490_000,
    oldPrice: 15_990_000,
    cpu: "i5-1235U",
    ram: "16GB",
    storage: "512GB",
    rating: 4.4,
    reviewCount: 63,
    installmentPerMonth: 1_124_000,
    gift: "Tặng balo",
    badge: "-16%",
    accent: "silver",
  },
  {
    id: "p-acer-nitro-5-tiger",
    slug: "acer-nitro-5-tiger-rtx-4050",
    name: "Acer Nitro 5 Tiger RTX 4050",
    brand: "Acer",
    price: 21_990_000,
    oldPrice: 25_990_000,
    cpu: "i7-13620H",
    ram: "16GB",
    storage: "RTX 4050",
    rating: 4.6,
    reviewCount: 88,
    installmentPerMonth: 1_832_000,
    badge: "-15%",
    accent: "crimson",
  },
  {
    id: "p-lenovo-ideapad-slim-5",
    slug: "lenovo-ideapad-slim-5-i5",
    name: "Lenovo IdeaPad Slim 5 i5",
    brand: "Lenovo",
    price: 16_490_000,
    oldPrice: 18_990_000,
    cpu: "i5-13420H",
    ram: "16GB",
    storage: "512GB",
    rating: 4.5,
    reviewCount: 57,
    installmentPerMonth: 1_374_000,
    accent: "blue",
  },
  {
    id: "p-lenovo-loq-15",
    slug: "lenovo-loq-15-rtx-4060",
    name: "Lenovo LOQ 15 RTX 4060",
    brand: "Lenovo",
    price: 25_490_000,
    oldPrice: 29_990_000,
    cpu: "i7-13650HX",
    ram: "16GB",
    storage: "RTX 4060",
    rating: 4.7,
    reviewCount: 104,
    installmentPerMonth: 2_124_000,
    gift: "Tặng tai nghe gaming",
    badge: "-15%",
    isNew: true,
    accent: "red",
  },
  {
    id: "p-hp-pavilion-15",
    slug: "hp-pavilion-15-i5",
    name: "HP Pavilion 15 i5",
    brand: "HP",
    price: 14_990_000,
    oldPrice: 17_490_000,
    cpu: "i5-1334U",
    ram: "8GB",
    storage: "512GB",
    rating: 4.3,
    reviewCount: 49,
    installmentPerMonth: 1_249_000,
    accent: "silver",
  },
  {
    id: "p-hp-victus-16",
    slug: "hp-victus-16-rtx-4060",
    name: "HP Victus 16 RTX 4060",
    brand: "HP",
    price: 23_990_000,
    oldPrice: 27_990_000,
    cpu: "i7-13700H",
    ram: "16GB",
    storage: "RTX 4060",
    rating: 4.6,
    reviewCount: 71,
    installmentPerMonth: 1_999_000,
    gift: "Tặng balo + chuột",
    badge: "-14%",
    accent: "dark",
  },
  {
    id: "p-macbook-air-m2-13",
    slug: "macbook-air-m2-13-inch",
    name: "MacBook Air M2 13 inch",
    brand: "MacBook",
    price: 21_990_000,
    oldPrice: 24_990_000,
    cpu: "Apple M2",
    ram: "8GB",
    storage: "256GB",
    rating: 4.8,
    reviewCount: 187,
    installmentPerMonth: 1_832_000,
    gift: "Tặng túi chống sốc",
    badge: "-12%",
    accent: "silver",
  },
  {
    id: "p-macbook-pro-14-m3",
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14 M3",
    brand: "MacBook",
    price: 39_990_000,
    oldPrice: 44_990_000,
    cpu: "Apple M3",
    ram: "16GB",
    storage: "512GB",
    rating: 4.9,
    reviewCount: 143,
    installmentPerMonth: 3_332_000,
    badge: "-11%",
    isNew: true,
    accent: "dark",
  },
];

// Shop bán cả máy MỚI & CŨ -> lọc theo tình trạng + hãng + nhu cầu (tiện SEO).
// (Laptop mới VẪN là danh mục — chỉ ẩn khỏi thanh nav trên đầu, xem CategoryNav.)
export const CATEGORIES: Category[] = [
  { slug: "laptop-moi", name: "Laptop mới", icon: "new" },
  { slug: "laptop-cu", name: "Laptop cũ", icon: "used", tag: "Giá tốt" },
  { slug: "dell", name: "Dell", icon: "dell", tag: "Nhiều mẫu" },
  { slug: "hp", name: "HP", icon: "hp" },
  { slug: "lenovo", name: "Lenovo", icon: "lenovo" },
  { slug: "asus", name: "Asus", icon: "asus" },
  { slug: "acer", name: "Acer", icon: "acer" },
  { slug: "msi", name: "MSI", icon: "msi" },
  { slug: "macbook", name: "MacBook", icon: "macbook" },
  { slug: "laptop-gaming", name: "Laptop Gaming", icon: "gaming" },
  { slug: "laptop-do-hoa", name: "Máy trạm - Đồ họa", icon: "graphic" },
  { slug: "laptop-van-phong", name: "Laptop văn phòng", icon: "office" },
  { slug: "pc", name: "PC đồng bộ", icon: "pc" },
  { slug: "man-hinh", name: "Màn hình", icon: "monitor" },
  { slug: "phu-kien", name: "Sạc & Phụ kiện", icon: "accessory" },
];

// Trợ giúp gọn khi khai báo bài viết mẫu (mỗi dòng 1 đoạn / 1 tiêu đề).
// Nội dung bài viết nay là HTML (khớp CKEditor) -> 2 hàm này xuất thẳng HTML.
const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const t = (value: string): string => `<p>${esc(value)}</p>`;
// h2: bài viết có h1 = tên bài -> các mục là h2 (đúng cấp bậc SEO).
const h = (value: string): string => `<h2>${esc(value)}</h2>`;

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "mua-laptop-cu-o-dau-uy-tin-tai-da-nang",
    tag: "Tư vấn",
    title: "Mua laptop cũ ở đâu uy tín tại Đà Nẵng? Kinh nghiệm chọn nơi mua 2026",
    readMinutes: 7,
    date: "30/07/2026",
    accent: "green",
    excerpt:
      "Mua laptop cũ tại Đà Nẵng ở đâu uy tín, tránh mua nhầm máy dựng, pin chai? Bài viết tổng hợp tiêu chí chọn cửa hàng và kinh nghiệm chọn máy cũ đáng tiền năm 2026.",
    content: [
      `<p>Laptop cũ là lựa chọn thông minh giúp bạn sở hữu cấu hình cao với chi phí chỉ bằng 50–70% máy mới. Nhưng thị trường <strong>laptop cũ tại Đà Nẵng</strong> cũng đầy rủi ro: máy dựng, pin chai, linh kiện thay lô. Vậy mua ở đâu uy tín và làm sao chọn được máy tốt? Dưới đây là kinh nghiệm thực tế.</p>`,
      `<h2>Vì sao nên mua laptop cũ năm 2026?</h2>`,
      `<p>Một chiếc laptop văn phòng hay doanh nhân đời 2022–2023 giờ đã rớt giá mạnh nhưng cấu hình vẫn thừa sức đáp ứng học tập, làm việc trong nhiều năm tới. Với cùng ngân sách, mua máy cũ cao cấp (ThinkPad, Dell Latitude, EliteBook) thường bền và sướng tay hơn mua máy mới phổ thông. Đây là lý do <strong>laptop cũ giá rẻ tại Đà Nẵng</strong> ngày càng được sinh viên và dân văn phòng ưa chuộng.</p>`,
      `<h2>4 tiêu chí chọn nơi bán laptop cũ uy tín</h2>`,
      `<p><strong>1. Có cửa hàng thật, địa chỉ rõ ràng.</strong> Tuyệt đối ưu tiên nơi có mặt bằng để bạn xem máy trực tiếp, tránh giao dịch trôi nổi trên mạng xã hội không địa chỉ.</p>`,
      `<p><strong>2. Chính sách bảo hành minh bạch.</strong> Máy cũ tốt phải có bảo hành tối thiểu 3–6 tháng và cam kết 1 đổi 1 trong thời gian đầu nếu lỗi.</p>`,
      `<p><strong>3. Cho kiểm tra máy thoải mái trước khi mua.</strong> Nơi uy tín luôn để bạn test pin, màn hình, bàn phím, cổng kết nối bằng phần mềm ngay tại chỗ.</p>`,
      `<p><strong>4. Đánh giá thật từ khách hàng.</strong> Xem review trên Google Maps, Facebook để đánh giá độ tin cậy trước khi tới.</p>`,
      `<h2>Những rủi ro thường gặp khi mua máy cũ</h2>`,
      `<ul><li><strong>Pin chai nặng</strong> — dung lượng thiết kế còn dưới 70%, dùng được chưa tới 2 tiếng.</li><li><strong>Máy dựng</strong> — main đã sửa chữa, dễ hỏng lại.</li><li><strong>Thay màn, thay bàn phím lô</strong> — chất lượng kém máy zin.</li><li><strong>Thổi cấu hình</strong> — quảng cáo một đằng, linh kiện bên trong một nẻo.</li></ul>`,
      `<p>Cách phòng tránh tốt nhất là chọn nơi kiểm định kỹ và cho phép bạn test. Xem thêm bài <a href="/blog/cach-kiem-tra-laptop-cu-truoc-khi-mua-checklist">checklist 10 bước kiểm tra laptop cũ trước khi mua</a> để tự tin hơn khi đi xem máy.</p>`,
      `<h2>Nên chọn dòng máy cũ nào?</h2>`,
      `<p>Nếu cần <strong>máy văn phòng bền, pin tốt</strong>, hãy nhắm ThinkPad, Dell Latitude, HP EliteBook — dòng doanh nghiệp làm rất chắc chắn. Cần <strong>mỏng nhẹ cao cấp</strong> thì Dell XPS, LG Gram. Cần <strong>chơi game</strong> thì các dòng gaming đời trước có card rời vẫn rất đáng tiền — tham khảo <a href="/blog/top-5-laptop-gaming-cu-gia-re-da-nang-2026">top laptop gaming cũ giá rẻ tại Đà Nẵng</a>.</p>`,
      `<h2>Mua laptop cũ uy tín tại Đà Nẵng ở đâu?</h2>`,
      `<p><strong>Laptop Chính Nguyễn</strong> có sẵn hơn 140 mẫu <a href="/laptop-cu">laptop cũ đã kiểm định</a>, tất cả được test kỹ pin và linh kiện, bảo hành rõ ràng, hỗ trợ <a href="/thu-cu-doi-moi">thu cũ đổi mới</a> và trả góp 0%. Bạn có thể tới xem máy trực tiếp tại <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> (mở cửa 8:00–21:00 tất cả các ngày). Cần tư vấn chọn máy đúng nhu cầu, gọi ngay hotline <strong>0936.122.144</strong> hoặc xem <a href="/san-pham">toàn bộ sản phẩm đang bán</a>.</p>`,
    ].join(""),
  },
  {
    slug: "top-5-laptop-gaming-cu-gia-re-da-nang-2026",
    tag: "Tư vấn",
    title: "Top 5 dòng laptop gaming cũ giá rẻ đáng mua tại Đà Nẵng 2026",
    readMinutes: 7,
    date: "28/07/2026",
    accent: "blue",
    excerpt:
      "Ngân sách hạn chế vẫn muốn chơi game mượt? Đây là 5 dòng laptop gaming cũ giá rẻ đáng mua nhất tại Đà Nẵng năm 2026, kèm mẹo chọn máy cũ còn card khỏe.",
    content: [
      `<p>Không phải ai cũng đủ ngân sách mua laptop gaming mới. Tin vui là các mẫu <strong>laptop gaming cũ giá rẻ tại Đà Nẵng</strong> đời 2021–2023 vẫn thừa sức chiến game AAA ở Full HD, mà giá chỉ còn một nửa. Dưới đây là 5 dòng đáng mua nhất năm 2026.</p>`,
      `<h2>1. Acer Nitro 5 — vua phổ thông</h2>`,
      `<p>Nitro 5 là dòng laptop gaming bán chạy nhất phân khúc giá rẻ. Bản dùng RTX 3050/3060 tản nhiệt tốt, dễ nâng cấp RAM và SSD, linh kiện phổ biến nên bảo hành thay thế dễ. Rất hợp cho học sinh, sinh viên mới chơi game.</p>`,
      `<h2>2. Asus TUF Gaming — bền bỉ, chuẩn quân đội</h2>`,
      `<p>Dòng TUF nổi tiếng khung máy chắc chắn, đạt chuẩn độ bền quân sự MIL-STD. Bản RTX 3050 Ti/3060 cũ có giá rất mềm, pin và tản ổn định, xứng đáng nếu bạn cần một cỗ máy "trâu bò" dùng lâu dài.</p>`,
      `<h2>3. Lenovo LOQ / Legion — mát và yên tĩnh</h2>`,
      `<p>Legion đời cũ có hệ thống tản nhiệt Coldfront xuất sắc, chơi lâu vẫn mát và êm. Bàn phím gõ sướng, màn hình đẹp. Đây là lựa chọn cao cấp hơn trong tầm giá cũ, phù hợp người vừa chơi game vừa làm việc.</p>`,
      `<h2>4. HP Victus — thiết kế trẻ trung</h2>`,
      `<p>Victus mang thiết kế gọn gàng, không quá "hầm hố", hợp cả đi học lẫn đi làm. Bản RTX 3050/4050 cũ cân tốt game phổ thông và các phần mềm đồ họa nhẹ.</p>`,
      `<h2>5. MSI GF / Katana — hiệu năng trên giá thành</h2>`,
      `<p>Các dòng MSI tầm trung cũ thường có cấu hình CPU khỏe (dòng H) so với giá. Nếu bạn ưu tiên sức mạnh xử lý để vừa chơi vừa stream, đây là ứng viên đáng cân nhắc.</p>`,
      `<h2>Mẹo chọn laptop gaming cũ còn "khỏe"</h2>`,
      `<ul><li><strong>Kiểm tra nhiệt độ khi tải nặng:</strong> chạy thử game hoặc stress test, CPU/GPU không nên vượt 90°C liên tục.</li><li><strong>Xem tình trạng quạt tản nhiệt:</strong> nghe tiếng quạt, hỏi lịch sử vệ sinh máy.</li><li><strong>Chú ý TGP của card:</strong> cùng tên card nhưng bản điện cao chơi mạnh hơn hẳn.</li><li><strong>Test đủ số điểm ảnh màn hình</strong> để tránh điểm chết.</li></ul>`,
      `<p>Chi tiết cách test có trong bài <a href="/blog/cach-kiem-tra-laptop-cu-truoc-khi-mua-checklist">kiểm tra laptop cũ trước khi mua</a>. Nếu quan tâm dòng card mới hơn, đọc thêm <a href="/blog/laptop-gaming-rtx-4060-tam-gia-nao-2026">laptop gaming RTX 4060 tầm giá nào</a>.</p>`,
      `<h2>Mua laptop gaming cũ tại Đà Nẵng ở đâu?</h2>`,
      `<p>Xem ngay danh mục <a href="/laptop-gaming">laptop gaming</a> tại <strong>Laptop Chính Nguyễn</strong> — máy cũ được test card, tản nhiệt và pin kỹ lưỡng, bảo hành minh bạch, trả góp 0%. Ghé <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> để chơi thử máy, hoặc gọi <strong>0936.122.144</strong> để được tư vấn cấu hình hợp túi tiền.</p>`,
    ].join(""),
  },
  {
    slug: "kinh-nghiem-chon-laptop-may-tram-do-hoa-render",
    tag: "Tư vấn",
    title: "Kinh nghiệm chọn laptop máy trạm cho đồ họa, render tại Đà Nẵng",
    readMinutes: 8,
    date: "25/07/2026",
    accent: "purple",
    excerpt:
      "Laptop máy trạm (workstation) khác gì laptop thường? Kinh nghiệm chọn máy trạm cho đồ họa, render 3D, dựng phim đúng nhu cầu và tiết kiệm chi phí tại Đà Nẵng.",
    content: [
      `<p>Với dân thiết kế, kiến trúc, dựng phim hay kỹ thuật, một chiếc <strong>laptop máy trạm tại Đà Nẵng</strong> đúng nhu cầu sẽ giúp render nhanh, chạy phần mềm nặng ổn định suốt ngày dài. Nhưng máy trạm không rẻ, chọn sai rất phí tiền. Đây là kinh nghiệm chọn máy.</p>`,
      `<h2>Laptop máy trạm khác gì laptop thường?</h2>`,
      `<p>Workstation được thiết kế để chạy tải nặng liên tục nhiều giờ mà vẫn ổn định. Điểm khác biệt nằm ở: card đồ họa chuyên dụng (NVIDIA RTX / trước đây là Quadro) được tối ưu driver cho phần mềm CAD/3D, tùy chọn <strong>RAM ECC</strong> chống lỗi bộ nhớ, khung máy và tản nhiệt bền hơn, cùng chứng nhận ISV từ các hãng phần mềm lớn (Autodesk, Adobe, SolidWorks).</p>`,
      `<h2>Chọn cấu hình theo phần mềm bạn dùng</h2>`,
      `<p><strong>Dựng phim, Premiere/DaVinci:</strong> ưu tiên CPU nhiều nhân, RAM 32GB trở lên, card mạnh để tăng tốc xuất video.</p>`,
      `<p><strong>3D, render (Blender, 3ds Max, V-Ray):</strong> card đồ họa và VRAM là yếu tố quyết định — nên chọn card có VRAM 8GB trở lên.</p>`,
      `<p><strong>CAD, kiến trúc (AutoCAD, Revit, SolidWorks):</strong> ưu tiên xung nhịp CPU cao và card có driver chuyên dụng để chạy mượt viewport.</p>`,
      `<p><strong>Thiết kế 2D, chỉnh ảnh:</strong> không cần máy trạm hạng nặng — một laptop đồ họa card rời tầm trung là đủ, xem danh mục <a href="/laptop-do-hoa-ky-thuat">laptop đồ họa - kỹ thuật</a>.</p>`,
      `<h2>Các dòng máy trạm đáng mua</h2>`,
      `<ul><li><strong>Dell Precision</strong> — bền, linh kiện dễ thay, dịch vụ tốt.</li><li><strong>HP ZBook</strong> — thiết kế đẹp, màn hình chuẩn màu cho dân sáng tạo.</li><li><strong>Lenovo ThinkPad P Series</strong> — bàn phím tuyệt vời, độ tin cậy cao.</li></ul>`,
      `<p>Bản cũ của các dòng này rất đáng tiền: giá mềm hơn nhiều nhưng hiệu năng vẫn thừa cho công việc chuyên nghiệp.</p>`,
      `<h2>Nên mua máy trạm hay laptop gaming?</h2>`,
      `<p>Đây là câu hỏi rất phổ biến. Laptop gaming có card mạnh, giá rẻ hơn nhưng thiếu tối ưu driver chuyên nghiệp; máy trạm ổn định và chuẩn màu hơn nhưng đắt. Mình phân tích chi tiết trong bài <a href="/blog/laptop-render-3d-chon-may-tram-hay-gaming">laptop render 3D: chọn máy trạm hay gaming</a>.</p>`,
      `<h2>Mua laptop máy trạm tại Đà Nẵng ở đâu?</h2>`,
      `<p>Xem danh mục <a href="/may-tram">laptop máy trạm</a> tại <strong>Laptop Chính Nguyễn</strong> — có sẵn Dell Precision, HP ZBook, ThinkPad P đã kiểm định, bảo hành uy tín, hỗ trợ trả góp 0%. Đội ngũ tư vấn sẽ giúp bạn khớp cấu hình với đúng phần mềm đang dùng. Ghé <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> hoặc gọi <strong>0936.122.144</strong>.</p>`,
    ].join(""),
  },
  {
    slug: "dell-xps-13-vs-xps-15-nen-mua-ban-nao",
    tag: "So sánh",
    title: "Dell XPS 13 vs XPS 15: nên mua bản nào? So sánh chi tiết 2026",
    readMinutes: 7,
    date: "22/07/2026",
    accent: "blue",
    excerpt:
      "Dell XPS 13 hay XPS 15 hợp với bạn hơn? So sánh chi tiết màn hình, hiệu năng, pin, cân nặng và giá để chọn đúng chiếc Dell XPS tại Đà Nẵng năm 2026.",
    content: [
      `<p><strong>Dell XPS</strong> là dòng laptop mỏng nhẹ cao cấp được yêu thích nhất nhờ thiết kế sang, màn hình đẹp và build chắc chắn. Nhưng nên chọn <strong>XPS 13</strong> nhỏ gọn hay <strong>XPS 15</strong> mạnh mẽ? Bài viết so sánh chi tiết để bạn quyết định.</p>`,
      `<h2>Bảng so sánh nhanh</h2>`,
      `<table><thead><tr><th>Tiêu chí</th><th>XPS 13</th><th>XPS 15</th></tr></thead><tbody>`,
      `<tr><td>Kích thước màn</td><td>13.4 inch</td><td>15.6 inch</td></tr>`,
      `<tr><td>Cân nặng</td><td>~1.2 kg</td><td>~1.9 kg</td></tr>`,
      `<tr><td>Card đồ họa</td><td>Tích hợp</td><td>Có tùy chọn RTX rời</td></tr>`,
      `<tr><td>Pin thực tế</td><td>Lâu hơn</td><td>Khá, tùy cấu hình</td></tr>`,
      `<tr><td>Hợp với</td><td>Di động, văn phòng</td><td>Sáng tạo, đồ họa nhẹ</td></tr>`,
      `</tbody></table>`,
      `<h2>XPS 13 — cho người ưu tiên di động</h2>`,
      `<p>Nếu bạn thường xuyên di chuyển, làm việc ở quán cà phê hay đi công tác, XPS 13 là lựa chọn lý tưởng: mỏng nhẹ chỉ hơn 1kg, pin bền, bỏ balo gọn gàng. Cấu hình dùng chip tiết kiệm điện thừa sức cho công việc văn phòng, lập trình web, học online và giải trí.</p>`,
      `<h2>XPS 15 — cho người cần màn lớn và sức mạnh</h2>`,
      `<p>XPS 15 có màn 15.6 inch rộng rãi, độ phủ màu tốt và tùy chọn card RTX rời — hợp cho chỉnh ảnh, dựng video nhẹ, thiết kế 2D. Đổi lại máy nặng và đắt hơn. Nếu công việc cần render nặng thật sự, hãy cân nhắc <a href="/may-tram">laptop máy trạm</a> thay vì XPS 15.</p>`,
      `<h2>Nên mua XPS mới hay cũ?</h2>`,
      `<p>Dell XPS giữ giá tốt và rất bền, nên bản cũ đời 2022–2023 là món hời: bạn có máy cao cấp với giá dễ chịu hơn nhiều. Chỉ cần mua ở nơi kiểm định kỹ pin và màn hình. Tham khảo <a href="/blog/cach-kiem-tra-laptop-cu-truoc-khi-mua-checklist">checklist kiểm tra laptop cũ</a> trước khi chốt.</p>`,
      `<h2>Kết luận: chọn bản nào?</h2>`,
      `<p>Chọn <strong>XPS 13</strong> nếu ưu tiên nhẹ, pin lâu, dùng văn phòng và di chuyển nhiều. Chọn <strong>XPS 15</strong> nếu cần màn lớn, làm sáng tạo và không ngại máy nặng hơn.</p>`,
      `<h2>Mua Dell XPS tại Đà Nẵng ở đâu?</h2>`,
      `<p>Xem các mẫu <a href="/dell">Dell XPS 13, XPS 15</a> chính hãng và cũ tại <strong>Laptop Chính Nguyễn</strong> — kiểm định kỹ, bảo hành rõ ràng, trả góp 0%. Ghé thử máy tại <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> hoặc gọi <strong>0936.122.144</strong> để được tư vấn.</p>`,
    ].join(""),
  },
  {
    slug: "cach-kiem-tra-laptop-cu-truoc-khi-mua-checklist",
    tag: "Thủ thuật",
    title: "Cách kiểm tra laptop cũ trước khi mua: checklist 10 bước (2026)",
    readMinutes: 8,
    date: "20/07/2026",
    accent: "green",
    excerpt:
      "Checklist 10 bước kiểm tra laptop cũ trước khi mua: pin, màn hình, bàn phím, ổ cứng, nhiệt độ… giúp bạn tránh mua nhầm máy dựng, pin chai khi mua laptop cũ.",
    content: [
      `<p>Mua <strong>laptop cũ</strong> tiết kiệm được nhiều tiền, nhưng chỉ khi bạn biết cách kiểm tra. Dưới đây là checklist 10 bước đơn giản mà ai cũng làm được ngay tại cửa hàng để tránh mua nhầm máy lỗi.</p>`,
      `<h2>1. Kiểm tra ngoại hình tổng thể</h2>`,
      `<p>Quan sát vỏ máy, bản lề, các cạnh xem có nứt, móp, dấu hiệu tháo mở nhiều lần không. Bản lề lỏng hoặc kêu là dấu hiệu máy đã dùng nặng.</p>`,
      `<h2>2. Test màn hình tìm điểm chết</h2>`,
      `<p>Mở lần lượt màn hình đơn sắc đỏ, xanh lá, xanh dương, trắng, đen để phát hiện điểm chết, hở sáng, ố màn. Đây là lỗi rất tốn tiền để sửa.</p>`,
      `<h2>3. Kiểm tra tình trạng pin (quan trọng nhất)</h2>`,
      `<p>Trên Windows, mở PowerShell gõ lệnh tạo báo cáo pin để xem dung lượng thiết kế và dung lượng thực tế. Pin còn trên 80% là tốt; dưới 70% nên cân nhắc thay hoặc trừ giá.</p>`,
      `<h2>4. Test toàn bộ bàn phím</h2>`,
      `<p>Dùng trang test bàn phím online, bấm thử từng phím xem có phím liệt, kẹt không. Kiểm tra cả đèn nền bàn phím nếu có.</p>`,
      `<h2>5. Kiểm tra touchpad và các nút</h2>`,
      `<p>Rê thử touchpad ở mọi góc, test click trái/phải, cử chỉ đa điểm.</p>`,
      `<h2>6. Test loa, micro và webcam</h2>`,
      `<p>Phát một video để nghe loa có rè, mất tiếng không; mở camera và ghi âm thử micro.</p>`,
      `<h2>7. Kiểm tra tất cả cổng kết nối</h2>`,
      `<p>Cắm thử USB, HDMI, jack tai nghe, đầu đọc thẻ và cổng sạc — đảm bảo mọi cổng đều nhận.</p>`,
      `<h2>8. Xem "sức khỏe" ổ cứng SSD</h2>`,
      `<p>Dùng phần mềm như CrystalDiskInfo để xem tình trạng (Health) và số giờ hoạt động của ổ. Ổ báo "Caution" là dấu hiệu sắp hỏng.</p>`,
      `<h2>9. Kiểm tra nhiệt độ khi tải nặng</h2>`,
      `<p>Chạy một tác vụ nặng vài phút và theo dõi nhiệt độ CPU/GPU. Máy nóng bất thường hoặc tự tắt là dấu hiệu tản nhiệt kém hoặc lỗi phần cứng.</p>`,
      `<h2>10. Đối chiếu cấu hình thực tế</h2>`,
      `<p>Vào thông tin hệ thống để kiểm tra đúng CPU, RAM, dung lượng ổ như quảng cáo — tránh bị "thổi" cấu hình.</p>`,
      `<h2>Mẹo cuối: chọn nơi bán uy tín</h2>`,
      `<p>Cách chắc ăn nhất vẫn là mua ở nơi kiểm định sẵn và cho bạn test thoải mái. Xem thêm <a href="/blog/mua-laptop-cu-o-dau-uy-tin-tai-da-nang">mua laptop cũ ở đâu uy tín tại Đà Nẵng</a>. Toàn bộ <a href="/laptop-cu">laptop cũ tại Laptop Chính Nguyễn</a> đều được test 10 bước như trên trước khi lên kệ, bảo hành minh bạch. Ghé <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> hoặc gọi <strong>0936.122.144</strong> để được hỗ trợ.</p>`,
    ].join(""),
  },
  {
    slug: "laptop-gaming-rtx-4060-tam-gia-nao-2026",
    tag: "Tư vấn",
    title: "Laptop gaming RTX 4060 tầm giá nào? Gợi ý cấu hình 2026",
    readMinutes: 6,
    date: "16/07/2026",
    accent: "blue",
    excerpt:
      "Laptop gaming RTX 4060 giá bao nhiêu, chơi game gì mượt và nên chọn cấu hình nào năm 2026? Gợi ý chi tiết cho game thủ tại Đà Nẵng với ngân sách hợp lý.",
    content: [
      `<p><strong>RTX 4060 Laptop</strong> là card đồ họa "quốc dân" của game thủ tầm trung: đủ mạnh để chơi mọi game AAA ở Full HD thiết lập cao, giá lại hợp lý. Vậy <strong>laptop gaming RTX 4060 tại Đà Nẵng</strong> tầm giá nào và nên chọn cấu hình ra sao? Cùng phân tích.</p>`,
      `<h2>RTX 4060 Laptop mạnh cỡ nào?</h2>`,
      `<p>Nhờ công nghệ DLSS 3 với Frame Generation, RTX 4060 tăng khung hình mạnh trong các game hỗ trợ, chơi mượt hầu hết tựa game hiện nay ở độ phân giải Full HD (1080p) và cả 2K với thiết lập hợp lý. Với 8GB VRAM, card này cũng làm tốt các tác vụ dựng video, đồ họa nhẹ.</p>`,
      `<h2>Lưu ý quan trọng: TGP quyết định sức mạnh</h2>`,
      `<p>Cùng tên RTX 4060 nhưng mỗi máy cấu hình điện (TGP) khác nhau — bản chạy công suất cao (như 140W) sẽ mạnh hơn đáng kể bản điện thấp (như 75W). Khi mua, hãy hỏi rõ TGP và ưu tiên máy có <strong>MUX Switch</strong> để tối đa FPS khi chơi.</p>`,
      `<h2>Cấu hình nên đi kèm RTX 4060</h2>`,
      `<ul><li><strong>CPU:</strong> Intel Core i7 dòng H hoặc Ryzen 7 để không nghẽn cổ chai.</li><li><strong>RAM:</strong> tối thiểu 16GB, nên nâng 32GB nếu vừa chơi vừa stream.</li><li><strong>Màn hình:</strong> Full HD 144Hz trở lên cho trải nghiệm mượt.</li><li><strong>SSD:</strong> 512GB NVMe trở lên vì game ngày càng nặng.</li></ul>`,
      `<h2>Nên mua mới hay cũ?</h2>`,
      `<p>Nếu ngân sách hạn chế, một chiếc RTX 4060 cũ còn bảo hành, được test kỹ card và tản nhiệt là rất đáng tiền. Bạn cũng có thể cân nhắc đời card trước để tiết kiệm — xem <a href="/blog/top-5-laptop-gaming-cu-gia-re-da-nang-2026">top laptop gaming cũ giá rẻ tại Đà Nẵng</a>.</p>`,
      `<h2>Mua laptop gaming RTX 4060 tại Đà Nẵng ở đâu?</h2>`,
      `<p>Xem các mẫu trong danh mục <a href="/laptop-gaming">laptop gaming</a> tại <strong>Laptop Chính Nguyễn</strong> — có cả máy mới và cũ RTX 4060 với nhiều mức TGP, bảo hành rõ ràng, trả góp 0%. Ghé <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> để chơi thử, hoặc gọi <strong>0936.122.144</strong> để được tư vấn cấu hình đúng nhu cầu.</p>`,
    ].join(""),
  },
  {
    slug: "co-nen-mua-laptop-tra-gop-0-tai-da-nang",
    tag: "Tư vấn",
    title: "Có nên mua laptop trả góp 0% tại Đà Nẵng? Điều kiện & thủ tục 2026",
    readMinutes: 6,
    date: "12/07/2026",
    accent: "green",
    excerpt:
      "Mua laptop trả góp 0% tại Đà Nẵng có lợi không, cần điều kiện và thủ tục gì? Giải đáp chi tiết giúp bạn sở hữu laptop ngay mà không áp lực tài chính.",
    content: [
      `<p>Trả góp 0% giúp bạn sở hữu laptop ngay mà không phải trả thêm lãi, chia nhỏ chi phí hằng tháng. Nhưng <strong>mua laptop trả góp 0% tại Đà Nẵng</strong> có thật sự lợi và cần thủ tục gì? Bài viết giải đáp đầy đủ.</p>`,
      `<h2>Trả góp 0% là gì? Có "bẫy" không?</h2>`,
      `<p>Trả góp 0% nghĩa là tổng số tiền bạn trả bằng đúng giá máy, chia đều theo số tháng, không phát sinh lãi. Điều cần lưu ý là có thể có <strong>phí chuyển đổi trả góp</strong> hoặc phí hồ sơ nhỏ tùy đơn vị tài chính — hãy hỏi rõ tổng số tiền phải trả trước khi ký để không bất ngờ.</p>`,
      `<h2>2 hình thức trả góp phổ biến</h2>`,
      `<p><strong>Qua thẻ tín dụng:</strong> nhanh gọn nếu bạn đã có thẻ, chuyển đổi trả góp ngay tại quầy.</p>`,
      `<p><strong>Qua công ty tài chính (không cần thẻ):</strong> chỉ cần CCCD và một giấy tờ phụ, duyệt nhanh, phù hợp với sinh viên và người chưa có thẻ tín dụng.</p>`,
      `<h2>Điều kiện và thủ tục thường gặp</h2>`,
      `<ul><li>Đủ 18 tuổi trở lên, có CCCD.</li><li>Có thể cần thêm bằng lái xe hoặc giấy tờ phụ tùy gói.</li><li>Trả trước một phần (thường 10–30% giá máy) tùy chương trình.</li><li>Thời hạn linh hoạt 6–12 tháng.</li></ul>`,
      `<h2>Có nên mua trả góp không?</h2>`,
      `<p><strong>Nên</strong> nếu bạn cần máy gấp cho học tập, công việc mà chưa gom đủ tiền một lần, và khoản trả hằng tháng nằm trong khả năng. <strong>Cân nhắc</strong> nếu bạn đang có nhiều khoản vay khác. Với sinh viên, trả góp 0% là cách hợp lý để có ngay công cụ học tập — kết hợp chọn <a href="/blog/chon-laptop-cho-sinh-vien-2026-ngan-sach-15-trieu">laptop cho sinh viên tầm 15 triệu</a> để tối ưu ngân sách.</p>`,
      `<h2>Mẹo tiết kiệm hơn nữa</h2>`,
      `<p>Nếu muốn giảm số tiền trả mỗi tháng, cân nhắc <a href="/laptop-cu">laptop cũ đã kiểm định</a> (giá rẻ hơn nhiều mà vẫn được áp dụng trả góp), hoặc <a href="/thu-cu-doi-moi">thu cũ đổi mới</a> để lấy máy cũ bù vào giá máy mới.</p>`,
      `<h2>Mua laptop trả góp 0% tại Đà Nẵng ở đâu?</h2>`,
      `<p><strong>Laptop Chính Nguyễn</strong> hỗ trợ trả góp 0% cho cả laptop mới và cũ, thủ tục nhanh gọn ngay tại cửa hàng. Xem <a href="/san-pham">toàn bộ sản phẩm</a> rồi tới <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a>, hoặc gọi <strong>0936.122.144</strong> để được tư vấn gói trả góp phù hợp.</p>`,
    ].join(""),
  },
  {
    slug: "laptop-render-3d-chon-may-tram-hay-gaming",
    tag: "So sánh",
    title: "Laptop render 3D & dựng phim: nên chọn máy trạm hay laptop gaming?",
    readMinutes: 7,
    date: "08/07/2026",
    accent: "purple",
    excerpt:
      "Render 3D, dựng phim nên mua laptop máy trạm hay laptop gaming? So sánh hiệu năng, độ ổn định, chuẩn màu và giá để chọn đúng máy tại Đà Nẵng năm 2026.",
    content: [
      `<p>Khi cần một chiếc laptop để <strong>render 3D, dựng phim</strong>, nhiều người phân vân giữa <strong>laptop máy trạm</strong> và <strong>laptop gaming</strong>. Cả hai đều mạnh, nhưng được sinh ra cho hai mục đích khác nhau. Bài viết so sánh để bạn chọn đúng.</p>`,
      `<h2>Điểm giống nhau</h2>`,
      `<p>Cả hai đều có CPU khỏe và card đồ họa rời mạnh, đủ sức chạy Blender, Premiere, After Effects hay các phần mềm CAD. Về sức mạnh thô, một laptop gaming cao cấp có thể render nhanh ngang máy trạm cùng tầm giá.</p>`,
      `<h2>Khác biệt cốt lõi</h2>`,
      `<table><thead><tr><th>Tiêu chí</th><th>Máy trạm</th><th>Laptop gaming</th></tr></thead><tbody>`,
      `<tr><td>Driver phần mềm</td><td>Tối ưu ISV (CAD/3D)</td><td>Tối ưu cho game</td></tr>`,
      `<tr><td>Độ ổn định tải dài</td><td>Rất cao</td><td>Tốt</td></tr>`,
      `<tr><td>Màn chuẩn màu</td><td>Thường có</td><td>Tùy máy</td></tr>`,
      `<tr><td>RAM ECC</td><td>Có tùy chọn</td><td>Không</td></tr>`,
      `<tr><td>Giá</td><td>Cao hơn</td><td>Dễ chịu hơn</td></tr>`,
      `</tbody></table>`,
      `<h2>Khi nào nên chọn máy trạm?</h2>`,
      `<p>Chọn <a href="/may-tram">laptop máy trạm</a> nếu bạn làm chuyên nghiệp với CAD, kiến trúc, kỹ thuật (SolidWorks, Revit, AutoCAD) — nơi driver được chứng nhận giúp phần mềm chạy ổn định, ít lỗi; hoặc khi bạn cần render nặng nhiều giờ liên tục và cần màn chuẩn màu cho công việc thương mại.</p>`,
      `<h2>Khi nào laptop gaming là đủ?</h2>`,
      `<p>Chọn <a href="/laptop-gaming">laptop gaming</a> nếu bạn là freelancer, sinh viên hoặc người dựng phim/3D ở mức vừa phải, muốn tối ưu hiệu năng trên giá thành và tận dụng máy chơi game lúc rảnh. Một chiếc RTX 4060/4070 cân tốt phần lớn dự án — tham khảo <a href="/blog/laptop-gaming-rtx-4060-tam-gia-nao-2026">laptop gaming RTX 4060 tầm giá nào</a>.</p>`,
      `<h2>Kết luận</h2>`,
      `<p>Không có đáp án đúng cho tất cả: <strong>máy trạm</strong> thắng về độ ổn định và chuẩn nghề, <strong>laptop gaming</strong> thắng về hiệu năng trên giá. Hãy xuất phát từ phần mềm bạn dùng và ngân sách. Xem thêm <a href="/blog/kinh-nghiem-chon-laptop-may-tram-do-hoa-render">kinh nghiệm chọn laptop máy trạm cho đồ họa, render</a>.</p>`,
      `<h2>Tư vấn chọn máy render tại Đà Nẵng</h2>`,
      `<p><strong>Laptop Chính Nguyễn</strong> có cả laptop máy trạm và laptop gaming đã kiểm định, giúp bạn thử máy trực tiếp và chọn đúng nhu cầu render. Ghé <a href="/he-thong-cua-hang">hệ thống 4 cửa hàng tại Đà Nẵng &amp; Hội An</a> hoặc gọi <strong>0936.122.144</strong>.</p>`,
    ].join(""),
  },
  {
    slug: "back-to-school-2026-giam-gia-theo-diem-thi",
    tag: "Khuyến mãi",
    title:
      "Back To School 2026: giảm giá laptop theo điểm thi — điểm càng cao, giảm càng sâu (tới 1.5 triệu)",
    readMinutes: 5,
    date: "18/07/2026",
    accent: "green",
    excerpt:
      "Mùa tựu trường 2026, Laptop Chính Nguyễn tung chương trình Back To School độc đáo: giảm giá theo điểm thi đại học — điểm trên 9 giảm tới 1 triệu, cộng thêm 500K cho học sinh, sinh viên và giáo viên, kèm bộ quà tặng balo, túi chống sốc, mũ bảo hiểm.",
    content: [
      `<h2>Back To School 2026 tại Chính Nguyễn có gì đặc biệt?</h2>`,
      `<p>Mỗi mùa tựu trường, chọn được chiếc laptop ưng ý với chi phí hợp lý luôn là bài toán đau đầu của học sinh, sinh viên và phụ huynh. Năm nay, <strong>Laptop Chính Nguyễn</strong> mang đến chương trình <strong>Back To School 2026 — Giảm giá theo điểm thi</strong>: bạn thi càng tốt, mức giảm càng lớn. Đây là cách chúng tôi chúc mừng thành quả 12 năm đèn sách của các tân sinh viên Đà Nẵng.</p>`,
      `<h2>Bảng mức giảm theo điểm thi</h2>`,
      `<table><thead><tr><th>Đối tượng</th><th>Mức giảm</th></tr></thead><tbody>`,
      `<tr><td>Học sinh — sinh viên (có thẻ HSSV)</td><td><strong>300.000đ</strong></td></tr>`,
      `<tr><td>Thí sinh thi đại học có điểm trên 7</td><td><strong>400.000đ</strong></td></tr>`,
      `<tr><td>Thí sinh thi đại học điểm 7 — 8</td><td><strong>600.000đ</strong></td></tr>`,
      `<tr><td>Thí sinh thi đại học điểm 8 — 9</td><td><strong>800.000đ</strong></td></tr>`,
      `<tr><td>Thí sinh thi đại học điểm trên 9</td><td><strong>1.000.000đ</strong></td></tr>`,
      `</tbody></table>`,
      `<p>Bạn chỉ cần mang <strong>giấy báo điểm (hoặc tra cứu điểm thi trên điện thoại)</strong> và thẻ học sinh — sinh viên khi đến cửa hàng, nhân viên sẽ xác nhận và áp dụng mức giảm tương ứng ngay khi mua máy.</p>`,
      `<h2>Giảm thêm 500.000đ cho học sinh, sinh viên và giáo viên</h2>`,
      `<p>Ngoài mức giảm theo điểm thi, Chính Nguyễn <strong>giảm thêm 500.000đ</strong> cho tất cả khách hàng là học sinh, sinh viên và giáo viên. Ưu đãi được <strong>cộng dồn</strong> với bảng trên — nghĩa là một tân sinh viên có điểm thi trên 9 sẽ được giảm tổng cộng tới <strong>1.500.000đ</strong> khi mua laptop.</p>`,
      `<h2>Quà tặng đặc quyền kèm máy</h2>`,
      `<p>Mua laptop trong mùa Back To School 2026, bạn còn nhận bộ quà tặng đặc quyền để sẵn sàng nhập học:</p>`,
      `<ul><li><strong>Balo laptop</strong> — đựng máy và tài liệu gọn gàng tới giảng đường.</li><li><strong>Túi chống sốc</strong> — bảo vệ máy an toàn khi di chuyển.</li><li><strong>Mũ bảo hiểm Chính Nguyễn</strong> — đồng hành trên mọi cung đường đến trường.</li></ul>`,
      `<h2>Tư vấn 1-1: chọn máy đúng ngành, không lo mua dư cấu hình</h2>`,
      `<p>Mỗi ngành học cần một cấu hình khác nhau: kinh tế — ngoại ngữ chỉ cần máy văn phòng pin tốt, CNTT — kỹ thuật cần CPU mạnh và RAM 16GB, thiết kế — dựng phim cần card đồ họa rời. Đội ngũ Chính Nguyễn tư vấn <strong>1-1 miễn phí</strong> để bạn chọn đúng máy, đúng ngành, đúng ngân sách — gọi <strong>0938.122.144</strong> trước khi đến để được chuẩn bị sẵn máy trải nghiệm.</p>`,
      `<p>Tham khảo thêm: <a href="/blog/chon-laptop-cho-sinh-vien-2026-ngan-sach-15-trieu">Laptop cho sinh viên 2026: ngân sách 15 triệu nên mua gì?</a> hoặc xem <a href="/san-pham">toàn bộ laptop đang bán tại Chính Nguyễn</a>. Ngân sách eo hẹp? <a href="/laptop-cu">Laptop cũ đã kiểm định</a> cũng được áp dụng ưu đãi Back To School.</p>`,
      `<h2>Cách nhận ưu đãi</h2>`,
      `<ol><li>Chọn laptop phù hợp tại cửa hàng hoặc trên website, hoặc gọi hotline để được tư vấn.</li><li>Mang theo thẻ HSSV / thẻ giáo viên và giấy báo điểm thi (nếu có) khi mua máy.</li><li>Nhân viên xác nhận và trừ trực tiếp mức giảm vào giá máy, kèm bộ quà tặng.</li></ol>`,
      `<h2>Mua ở đâu? Liên hệ thế nào?</h2>`,
      `<p>Chương trình áp dụng tại tất cả cửa hàng Laptop Chính Nguyễn ở Đà Nẵng và Hội An, mở cửa 8:00 — 21:00 tất cả các ngày trong tuần:</p>`,
      `<ul><li><strong>175/8 Đỗ Quang</strong> - TP. Đà Nẵng</li><li><strong>605 Trần Cao Vân</strong> - TP. Đà Nẵng</li><li><strong>306/14 Nguyễn Hoàng</strong> - TP. Đà Nẵng</li><li><strong>139/2 Hùng Vương</strong>, TP. Hội An</li></ul>`,
      `<p>Liên hệ đặt hàng và tư vấn: <strong>0936.122.144</strong> — <strong>0938.122.144</strong>. Điểm cao — deal lớn — chọn đúng laptop: ghé Chính Nguyễn ngay trong mùa tựu trường này để nhận trọn ưu đãi Back To School 2026!</p>`,
    ].join(""),
  },
  {
    slug: "chon-laptop-cho-sinh-vien-2026-ngan-sach-15-trieu",
    tag: "Tư vấn",
    title: "Laptop cho sinh viên 2026: ngân sách 15 triệu nên mua gì?",
    readMinutes: 6,
    date: "08/07/2026",
    accent: "green",
    excerpt:
      "Với 15 triệu đồng năm 2026, sinh viên hoàn toàn có thể chọn được chiếc laptop bền, pin tốt và cấu hình đủ dùng cho cả học tập lẫn giải trí. Dưới đây là những tiêu chí và gợi ý cụ thể.",
    content: [
      h("Tầm giá 15 triệu năm 2026 mua được gì?"),
      t("Đây là phân khúc tối ưu nhất cho sinh viên. Nhờ công nghệ ngày càng rẻ, các mẫu máy dưới 15 triệu hiện đã đủ sức đáp ứng mọi nhu cầu học tập, học online, đa nhiệm nhiều tab Chrome và giải trí nhẹ nhàng — điều mà vài năm trước phải bỏ ra nhiều tiền hơn mới có."),
      h("Cấu hình nên ưu tiên"),
      t("CPU: Intel Core i5 thế hệ mới (gen 12–13) hoặc AMD Ryzen 5. RAM: nên chọn 16GB để chạy mượt các ứng dụng tích hợp AI và đa nhiệm — 8GB vẫn dùng được cho văn phòng cơ bản nhưng sẽ nhanh chật. Ổ cứng: SSD NVMe tối thiểu 512GB cho tốc độ khởi động nhanh và đủ chỗ lưu tài liệu, dự án."),
      h("Màn hình và thiết kế"),
      t("Kích thước lý tưởng là 14 inch (cân bằng hiển thị và di động) hoặc 15.6 inch nếu cần không gian lớn. Ưu tiên tỷ lệ 16:10 để xem được nhiều nội dung theo chiều dọc, độ phân giải Full HD trở lên, tấm nền IPS để góc nhìn rộng và đỡ mỏi mắt. Trọng lượng nên dưới 1.7kg cho dễ mang tới giảng đường, pin thực tế 8–12 giờ để yên tâm cả ngày."),
      h("Vài mẫu đáng cân nhắc"),
      t("Lenovo IdeaPad Slim 3 (Core i5, 16GB, SSD 512GB) và HP Pavilion 14 (Core i5, 16GB) là hai lựa chọn cân bằng nhất tầm giá này. Ngoài ra có Asus Vivobook 14 (mỏng nhẹ 1.4kg, chuẩn bền quân đội) và Acer Aspire 5 — đều là dòng phổ thông, bền bỉ và dễ bảo hành."),
      h("Chọn theo ngành học"),
      t("Ngành kinh tế, sư phạm, ngoại ngữ: card đồ họa tích hợp (Intel Iris Xe / AMD Radeon) là đủ. Ngành CNTT, kỹ thuật: ưu tiên CPU dòng H mạnh và RAM 16GB để chạy máy ảo, biên dịch mã. Ngành thiết kế, dựng phim: cần card rời RTX — thường phải nâng ngân sách lên trên 20 triệu."),
      h("Những bẫy nên tránh"),
      t("Đừng ham cấu hình giá rẻ ảo với chỉ 8GB RAM để tiết kiệm ban đầu — máy sẽ nhanh giật lag với ứng dụng năm 2026. Cũng đừng chọn laptop gaming quá nặng chỉ vì mạnh: mang vác mỗi ngày rất cực. Nếu chọn máy cũ, hãy mua ở nơi uy tín và kiểm tra kỹ pin, linh kiện trước khi quyết định."),
    ].join(""),
  },
  {
    slug: "laptop-gaming-rtx-5060-5070-tam-gia-20-30-trieu-2026",
    tag: "Tư vấn",
    title: "Laptop gaming 20–30 triệu 2026: chọn RTX 5060 hay RTX 5070?",
    readMinutes: 6,
    date: "05/07/2026",
    accent: "blue",
    excerpt:
      "Thế hệ RTX 50 (Blackwell) đưa laptop gaming tầm trung lên tầm cao mới. Nên chọn RTX 5060 hay cố lên RTX 5070? Bài viết giúp bạn quyết định.",
    content: [
      h("RTX 5060 hay RTX 5070?"),
      t("RTX 5060 được tối ưu cho độ phân giải Full HD và 2K — dư sức chơi hầu hết game AAA ở thiết lập cao. RTX 5070 (đặc biệt bản 12GB mới) mạnh hơn rõ rệt và hợp cho ai muốn chơi mượt ở 1440p có bật ray tracing, nhưng giá thường chạm ngưỡng 30 triệu."),
      h("Vì sao RTX 5060 đáng tiền năm 2026"),
      t("Kiến trúc Blackwell cải thiện hiệu năng và giảm nhiệt, đi kèm DLSS thế hệ mới giúp tăng khung hình mạnh trong game AAA cùng bộ nhớ GDDR7 nhanh hơn. Một số bài benchmark cho thấy RTX 5060 Mobile 115W còn nhỉnh hơn RTX 4070 Mobile 140W khoảng 12% ở cùng mức điện — một bước tiến đáng kể ở tầm trung."),
      h("Lưu ý quan trọng nhất: TGP"),
      t("TGP (Total Graphics Power) là yếu tố quyết định thường bị bỏ qua. Cùng là RTX 5070 nhưng bản chạy 60W cho hiệu năng khác hẳn bản 115W. Hãy luôn kiểm tra thông số TGP của từng model. Nên ưu tiên máy có MUX Switch / Advanced Optimus để tối ưu FPS khi chơi và tiết kiệm pin khi làm việc nhẹ."),
      h("Màn hình và tản nhiệt"),
      t("Nên chọn màn tần số quét 165Hz trở lên cho trải nghiệm mượt, độ phủ màu 100% sRGB hoặc DCI-P3 nếu bạn còn làm đồ họa/dựng phim. Đừng chỉ nhìn thông số: hãy đến showroom nghe thử độ ồn và cảm nhận nhiệt độ của hệ thống tản nhiệt khi máy chạy tải nặng."),
      h("Vài mẫu nổi bật"),
      t("Asus TUF Gaming RTX 5060 (màn 16 inch WUXGA 165Hz, có MUX Switch) và MSI RTX 5060 (màn QHD 165Hz, 100% DCI-P3, Core i7-14650HX) là lựa chọn cân bằng. Nếu ưu tiên di động, Asus TUF A14 (1.46kg, chuẩn quân sự) hay ROG Zephyrus G14 rất đáng xem — nhưng bản G14 cao cấp thường vượt 30 triệu."),
      h("Kết luận"),
      t("Trong tầm 20–30 triệu năm 2026, RTX 5060 là lựa chọn tối ưu hiệu năng trên giá thành cho phần lớn game thủ chơi ở Full HD/2K. Chỉ nên cố lên RTX 5070 12GB nếu bạn thực sự cần chơi 1440p có ray tracing và ngân sách cho phép."),
    ].join(""),
  },
  {
    slug: "intel-core-ultra-vs-amd-ryzen-ai-2026",
    tag: "So sánh",
    title: "Intel Core Ultra và AMD Ryzen AI 2026: nên chọn nền tảng nào?",
    readMinutes: 7,
    date: "02/07/2026",
    accent: "purple",
    excerpt:
      "Hai nền tảng CPU laptop hàng đầu 2026 với hai thế mạnh rõ rệt: Intel giỏi pin và di động, AMD mạnh hiệu năng và đồ họa tích hợp. Chọn cái nào là hợp với bạn?",
    content: [
      h("Hai nền tảng, hai thế mạnh"),
      t("Khác biệt lớn nhất giữa Intel Core Ultra Series 2 (Lunar Lake) và AMD Ryzen AI 300 (Strix Point) nằm ở hiệu suất pin, đồ họa tích hợp và định hướng sử dụng. Không có nền tảng nào 'thắng tuyệt đối' — chọn đúng phụ thuộc vào ưu tiên của bạn."),
      h("Pin và tính di động — Intel nhỉnh hơn"),
      t("Đây là khác biệt thực tế lớn nhất. Các máy Lunar Lake như XPS 13 hay ThinkPad X1 Carbon có thể đạt 16–20 giờ dùng hỗn hợp thực tế, trong khi laptop mỏng nhẹ dùng Ryzen AI 300 thường ở mức 10–12 giờ. Ở tác vụ nhẹ hằng ngày, Intel tiêu thụ điện thấp hơn hẳn."),
      h("Hiệu năng và đồ họa tích hợp — AMD chiếm ưu thế"),
      t("Về sức mạnh thô và đồ họa tích hợp, AMD thường dẫn trước. Kiến trúc Zen 5 tăng đáng kể số lệnh mỗi xung (IPC), thu hẹp khoảng cách xung nhịp với Intel. Đặc biệt, iGPU Radeon 890M trên Ryzen AI 300 mạnh gần bằng card rời phổ thông — lợi thế lớn cho người dựng nội dung hoặc chơi game nhẹ mà không cần GPU rời."),
      h("Khả năng AI (Copilot+) — gần như ngang nhau"),
      t("Cả Intel Core Ultra Series 2 lẫn AMD Ryzen AI 300 đều vượt mốc 40 TOPS mà Microsoft yêu cầu cho Copilot+. Trong thực tế, các tính năng AI (Live Captions, Windows Studio Effects, Cocreator…) chạy như nhau. Vì vậy đừng để 'Copilot+' là yếu tố quyết định — hãy chọn dựa trên pin, hiệu năng và giá."),
      h("Chơi game"),
      t("AMD tỏa sáng ở game thế giới mở và game nặng CPU nhiều nhân (Cyberpunk 2077, Flight Simulator, chiến thuật). Intel lại có lợi thế xung đơn nhân cao, hợp cho game esports cần FPS tối đa (Valorant, CS2)."),
      h("Vậy nên chọn cái nào?"),
      t("Chọn Intel Core Ultra Series 2 nếu pin và sự mỏng nhẹ là ưu tiên số một — cần 18+ giờ và máy siêu nhẹ. Chọn AMD Ryzen AI 300 nếu bạn cần hiệu năng cao, đồ họa tích hợp mạnh, làm sáng tạo hoặc chơi game linh hoạt với giá dễ chịu hơn. Lưu ý: thời lượng pin phụ thuộc nhiều vào thiết kế của từng máy chứ không chỉ ở logo CPU."),
    ].join(""),
  },
  {
    slug: "cach-bao-ve-tang-tuoi-tho-pin-laptop-2026",
    tag: "Thủ thuật",
    title: "6 cách bảo vệ và tăng tuổi thọ pin laptop (cập nhật 2026)",
    readMinutes: 5,
    date: "28/06/2026",
    accent: "green",
    excerpt:
      "Vài thói quen đơn giản dựa trên đặc tính pin lithium giúp viên pin laptop bền hơn, giữ dung lượng tốt qua nhiều năm. Tổng hợp lời khuyên mới nhất năm 2026.",
    content: [
      h("Vì sao pin bị chai?"),
      t("Pin lithium-ion bị 'stress' và xuống cấp nhanh khi thường xuyên sạc đầy 100% hoặc để cạn về 0%. Hiểu điều này là chìa khóa để dùng pin bền: mục tiêu là hạn chế thời gian pin nằm ở hai vùng cực đó."),
      h("1. Giữ pin trong khoảng 20–80%"),
      t("Đây là quy tắc quan trọng nhất và được nhắc lại nhiều nhất. Sạc khi pin còn khoảng 20% và rút ra quanh 80% giúp giảm áp lực hóa học lên pin, kéo dài đáng kể tuổi thọ mà gần như không ảnh hưởng trải nghiệm hằng ngày."),
      h("2. Bật giới hạn sạc 80% khi hay cắm điện"),
      t("Nếu máy chủ yếu để bàn và cắm sạc liên tục, hãy bật 'Conservation Mode' / giới hạn sạc 80% trong phần mềm của hãng: Lenovo Vantage, MyASUS, Dell Power Manager… Việc này có thể giảm mức độ chai pin khoảng 30% sau 2 năm mà bạn gần như không nhận ra khác biệt trong sử dụng."),
      h("3. Đừng để pin cạn về 0%"),
      t("Để máy chết hẳn cũng hại như sạc đầy liên tục. Một nghiên cứu trên hơn 10.000 laptop cho thấy máy được sạc 'nông' vẫn giữ 80% dung lượng sau 500 chu kỳ, trong khi máy hay xả sâu chỉ còn 80% sau 350 chu kỳ. Thói quen xả cạn rồi mới sạc là của pin nickel đời cũ — không còn đúng với pin lithium ngày nay."),
      h("4. Kiểm soát nhiệt độ — kẻ thù số một"),
      t("Nhiệt cao làm pin xuống cấp nhanh nhất. Đừng đặt máy trên chăn, nệm bịt khe tản nhiệt; vệ sinh quạt định kỳ; dùng đế tản nhiệt khi chạy tải nặng. Hạn chế lạm dụng sạc nhanh vì nó làm pin nóng hơn."),
      h("5. Cất giữ đúng cách"),
      t("Nếu không dùng máy trong thời gian dài, đừng cất khi pin đầy hoặc cạn — hãy để pin quanh 40–60% để giảm hao hụt dung lượng khi máy nằm im."),
      h("6. Kiểm tra sức khỏe pin định kỳ"),
      t("Trên Windows, mở Command Prompt (admin) và gõ lệnh powercfg /batteryreport để xem báo cáo pin. Đa số pin đạt 500–1.000 chu kỳ trước khi tụt dưới 80%. Chỉ nên thay pin khi dung lượng xuống dưới 65% và không trụ nổi 3 giờ tác vụ nhẹ."),
    ].join(""),
  },
];

// Các trang nội dung tĩnh cho phép chỉnh trong admin.
export interface StaticPageInfo {
  id: string;
  title: string;
  path: string;
}

export const STATIC_PAGES: StaticPageInfo[] = [
  { id: "gioi-thieu", title: "Giới thiệu", path: "/gioi-thieu" },
  { id: "lien-he", title: "Liên hệ", path: "/lien-he" },
  { id: "he-thong-cua-hang", title: "Hệ thống cửa hàng", path: "/he-thong-cua-hang" },
  { id: "thu-cu-doi-moi", title: "Thu cũ đổi mới", path: "/thu-cu-doi-moi" },
  { id: "bao-hanh", title: "Chính sách bảo hành", path: "/chinh-sach/bao-hanh" },
  { id: "doi-tra", title: "Chính sách đổi trả", path: "/chinh-sach/doi-tra" },
  { id: "giao-hang", title: "Chính sách giao hàng", path: "/chinh-sach/giao-hang" },
  { id: "tra-gop", title: "Chính sách trả góp", path: "/chinh-sach/tra-gop" },
  { id: "dieu-khoan", title: "Điều khoản sử dụng", path: "/chinh-sach/dieu-khoan" },
  { id: "bao-mat", title: "Chính sách bảo mật", path: "/chinh-sach/bao-mat" },
];

export function getStaticPage(id: string): StaticPageInfo | undefined {
  return STATIC_PAGES.find((p) => p.id === id);
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

export function getRelatedPosts(post: BlogPost, limit = 3): BlogPost[] {
  return BLOG_POSTS.filter((p) => p.slug !== post.slug).slice(0, limit);
}

// Gộp toàn bộ sản phẩm để tra cứu theo slug (trang chi tiết).
// Khi có DB: thay bằng prisma.product.findUnique({ where: { slug } }).
export const ALL_PRODUCTS: Product[] = [
  ...FLASH_SALE_PRODUCTS,
  ...FEATURED_PRODUCTS,
];

export function getProductBySlug(slug: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.slug === slug);
}

/** Sản phẩm liên quan: ưu tiên cùng hãng, rồi bù thêm cho đủ số lượng. */
export function getRelatedProducts(product: Product, limit = 4): Product[] {
  const sameBrand = ALL_PRODUCTS.filter(
    (p) => p.slug !== product.slug && p.brand === product.brand,
  );
  const others = ALL_PRODUCTS.filter(
    (p) => p.slug !== product.slug && p.brand !== product.brand,
  );
  return [...sameBrand, ...others].slice(0, limit);
}

// Nhóm danh mục cho mega-menu (thanh điều hướng).
export const CATEGORY_GROUPS: { title: string; slugs: string[] }[] = [
  {
    title: "Loại máy",
    slugs: ["laptop-moi", "laptop-cu"],
  },
  {
    title: "Theo thương hiệu",
    slugs: ["dell", "hp", "lenovo", "asus", "acer", "msi", "macbook"],
  },
  {
    title: "Theo nhu cầu",
    slugs: ["laptop-gaming", "laptop-do-hoa", "laptop-van-phong"],
  },
  {
    title: "Khác",
    slugs: ["pc", "man-hinh", "phu-kien"],
  },
];

// Link nhanh nổi bật trên thanh điều hướng.
export const QUICK_NAV_LINKS: { label: string; href: string; hot?: boolean }[] =
  [
    { label: "Tất cả sản phẩm", href: "/san-pham" },
    { label: "Laptop Gaming", href: "/laptop-gaming" },
    { label: "Văn phòng", href: "/laptop-van-phong" },
    { label: "MacBook", href: "/macbook" },
    { label: "Dell", href: "/dell" },
    { label: "Asus", href: "/asus" },
    { label: "Thu cũ đổi mới", href: "/thu-cu-doi-moi" },
    { label: "Trả góp 0%", href: "/chinh-sach/tra-gop" },
  ];

/** Các brand dùng làm tab lọc ở khối "Sản phẩm nổi bật". */
export const FEATURED_BRAND_TABS = [
  "Tất cả",
  "Dell",
  "Asus",
  "Acer",
  "Lenovo",
  "HP",
  "MacBook",
] as const;
